//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress_Teknik_Servis_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblArızaDetay
    {
        public int ArızaID { get; set; }
        public Nullable<int> İşlem { get; set; }
        public string Sorun { get; set; }
        public string Açıklama { get; set; }
        public Nullable<decimal> ÖnFiyat { get; set; }
        public Nullable<decimal> NetFiyat { get; set; }
        public string İşlemler { get; set; }
    }
}
