//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress_Teknik_Servis_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGider
    {
        public int GiderID { get; set; }
        public string GiderAçıklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<decimal> Tutar { get; set; }
    }
}
