//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress_Teknik_Servis_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblÜrünKabul
    {
        public int İşlemID { get; set; }
        public Nullable<int> Cari { get; set; }
        public Nullable<short> Personel { get; set; }
        public Nullable<System.DateTime> GelişTarih { get; set; }
        public Nullable<System.DateTime> ÇıkışTarih { get; set; }
        public string ÜrünSeriNo { get; set; }
    
        public virtual TblCari TblCari { get; set; }
        public virtual TblPersonel TblPersonel { get; set; }
    }
}
