//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress_Teknik_Servis_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblÜrünHareket
    {
        public int HareketID { get; set; }
        public Nullable<int> Ürün { get; set; }
        public Nullable<int> Müşteri { get; set; }
        public Nullable<short> Personel { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<short> Adet { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string ÜrünSeriNo { get; set; }
    
        public virtual TblCari TblCari { get; set; }
        public virtual TblPersonel TblPersonel { get; set; }
        public virtual TblÜrün TblÜrün { get; set; }
    }
}
